import { BLOG_POSTS_PER_PAGE, hygraphEndpoint } from '@/config'

// ─── Types ─────────────────────────────────────────────────────

export type PostAuthor = {
  name: string
  /** `avatar` is a 48×48 WebP crop generated by Hygraph */
  picture: { avatar: string } | null
}

export type CoverImage = {
  /** Original upload (full size, original format). Dimensions below describe this file. */
  url: string
  width: number | null
  height: number | null
  /** 480×300 and 800×500 WebP crops (16:10) for blog cards */
  cardSm: string
  cardLg: string
  /** 768px and 1536px wide WebP, aspect ratio preserved, for the post header */
  coverSm: string
  coverLg: string
  /** 1200×630 JPG for og:image / JSON-LD */
  og: string
}

export type PostSummary = {
  id: string
  title: string
  slug: string
  excerpt: string | null
  date: string | null
  publishedAt: string | null
  coverImage: CoverImage | null
  author: PostAuthor | null
}

export type PostDetail = PostSummary & {
  content: { markdown: string } | null
  updatedAt: string
}

export type PostsPage = {
  posts: PostSummary[]
  total: number
  totalPages: number
  page: number
}

// ─── Fetch helper ──────────────────────────────────────────────

type GraphQLResponse<T> = { data?: T; errors?: { message: string }[] }

async function hygraphFetch<T>(
  query: string,
  variables: Record<string, unknown> = {},
  signal?: AbortSignal
): Promise<T> {
  if (!hygraphEndpoint) {
    throw new Error('VITE_HYGRAPH_ENDPOINT is not set')
  }

  const res = await fetch(hygraphEndpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query, variables }),
    signal,
  })

  if (!res.ok) {
    throw new Error(`Hygraph request failed (${res.status})`)
  }

  const json = (await res.json()) as GraphQLResponse<T>
  if (json.errors?.length || !json.data) {
    throw new Error(json.errors?.map((e) => e.message).join('; ') ?? 'Empty Hygraph response')
  }
  return json.data
}

// ─── Queries ───────────────────────────────────────────────────

/**
 * Hygraph can resize and convert assets on the fly. Asking for these variants (instead of the
 * raw upload) keeps cards and headers to a few dozen KB instead of a multi-MB original.
 * `fit: crop` gives an exact box, `fit: max` only shrinks and keeps the aspect ratio.
 */
function assetVariant(
  alias: string,
  opts: { width: number; height?: number; fit: 'crop' | 'max'; format: 'webp' | 'jpg' }
): string {
  const size = `width: ${opts.width}${opts.height ? `, height: ${opts.height}` : ''}`
  return `${alias}: url(transformation: { image: { resize: { ${size}, fit: ${opts.fit} } }, document: { output: { format: ${opts.format} } } })`
}

const COVER_IMAGE_FIELDS = /* GraphQL */ `
  coverImage {
    url
    width
    height
    ${assetVariant('cardSm', { width: 480, height: 300, fit: 'crop', format: 'webp' })}
    ${assetVariant('cardLg', { width: 800, height: 500, fit: 'crop', format: 'webp' })}
    ${assetVariant('coverSm', { width: 768, fit: 'max', format: 'webp' })}
    ${assetVariant('coverLg', { width: 1536, fit: 'max', format: 'webp' })}
    ${assetVariant('og', { width: 1200, height: 630, fit: 'crop', format: 'jpg' })}
  }
`

const POST_SUMMARY_FIELDS = /* GraphQL */ `
  id
  title
  slug
  excerpt
  date
  publishedAt
  ${COVER_IMAGE_FIELDS}
  author {
    name
    picture {
      ${assetVariant('avatar', { width: 48, height: 48, fit: 'crop', format: 'webp' })}
    }
  }
`

const POSTS_PAGE_QUERY = /* GraphQL */ `
  query PostsPage($first: Int!, $skip: Int!) {
    posts(first: $first, skip: $skip, orderBy: date_DESC) {
      ${POST_SUMMARY_FIELDS}
    }
    postsConnection {
      aggregate {
        count
      }
    }
  }
`

const POST_BY_SLUG_QUERY = /* GraphQL */ `
  query PostBySlug($slug: String!) {
    post(where: { slug: $slug }) {
      ${POST_SUMMARY_FIELDS}
      updatedAt
      content {
        markdown
      }
    }
  }
`

const ALL_POST_SLUGS_QUERY = /* GraphQL */ `
  query AllPostSlugs($first: Int!, $skip: Int!) {
    posts(first: $first, skip: $skip, orderBy: date_DESC) {
      slug
      updatedAt
    }
  }
`

// ─── Public API ────────────────────────────────────────────────

export async function getPostsPage(page: number, signal?: AbortSignal): Promise<PostsPage> {
  const data = await hygraphFetch<{
    posts: PostSummary[]
    postsConnection: { aggregate: { count: number } }
  }>(
    POSTS_PAGE_QUERY,
    { first: BLOG_POSTS_PER_PAGE, skip: (page - 1) * BLOG_POSTS_PER_PAGE },
    signal
  )

  const total = data.postsConnection.aggregate.count
  return {
    posts: data.posts,
    total,
    totalPages: Math.max(1, Math.ceil(total / BLOG_POSTS_PER_PAGE)),
    page,
  }
}

/** Returns null when no post exists for the slug. */
export async function getPostBySlug(
  slug: string,
  signal?: AbortSignal
): Promise<PostDetail | null> {
  const data = await hygraphFetch<{ post: PostDetail | null }>(POST_BY_SLUG_QUERY, { slug }, signal)
  return data.post
}

/** Handy for a build-time sitemap script (Hygraph caps `first` at 100). */
export async function getAllPostSlugs(): Promise<{ slug: string; updatedAt: string }[]> {
  const all: { slug: string; updatedAt: string }[] = []
  for (let skip = 0; ; skip += 100) {
    const data = await hygraphFetch<{ posts: { slug: string; updatedAt: string }[] }>(
      ALL_POST_SLUGS_QUERY,
      { first: 100, skip }
    )
    all.push(...data.posts)
    if (data.posts.length < 100) break
  }
  return all
}

// ─── Helpers ───────────────────────────────────────────────────

/** Post `date` is a Hygraph Date (YYYY-MM-DD); fall back to publishedAt (ISO datetime). */
export function formatPostDate(post: Pick<PostSummary, 'date' | 'publishedAt'>): string | null {
  const raw = post.date ?? post.publishedAt
  if (!raw) return null
  return new Date(raw.slice(0, 10) + 'T00:00:00').toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

const HYGRAPH_ASSET_HOST = /(^|\.)graphassets\.com$/

/**
 * Images embedded in post content arrive as raw asset URLs, so resize and convert them with
 * Hygraph's URL transformations: `https://<host>/<id>/resize=width:800,fit:max/output=format:webp/<handle>`.
 * Anything that isn't an untransformed Hygraph asset URL is returned unchanged.
 */
export function optimizeAssetUrl(src: string, width: number): string {
  try {
    const url = new URL(src)
    if (!HYGRAPH_ASSET_HOST.test(url.hostname)) return src
    const segments = url.pathname.split('/').filter(Boolean)
    if (segments.some((s) => s.includes('='))) return src // already transformed
    const handle = segments.pop()
    if (!handle) return src
    url.pathname =
      '/' + [...segments, `resize=width:${width},fit:max`, 'output=format:webp', handle].join('/')
    return url.toString()
  } catch {
    return src
  }
}

/** Machine-readable ISO date for <time dateTime> and JSON-LD. */
export function postIsoDate(post: Pick<PostSummary, 'date' | 'publishedAt'>): string | null {
  return post.date ?? post.publishedAt ?? null
}
